### ISSUE TITLE
file path error on windows when using encodeBase64

### ISSUE THREAD

**Issue by tjx666** [JasonMejane/vscode-base64viewer#2]
![screenshot_2020-07-30_01-13-24](https://user-images.githubusercontent.com/41773861/88831418-e52db680-d201-11ea-8c12-2503ab8e7f9f.png)

I had made a pr to fix it https://github.com/JasonMejane/vscode-base64viewer/pull/1

**Comment by JasonMejane** [comment]
PR #1 accepted and merged to fix this issue
