### ISSUE TITLE
Request: Ability to call decode command programmatically

### ISSUE THREAD

**Issue by LennartKoot** [JasonMejane/vscode-base64viewer#20]
We have an extension that would like to call the decode function programmatically. Since we already know the base64 string we don't need the input box that is shown now.

We would like to be able to call the function using 
```typescript
vscode.commands.executeCommand('base64viewer.decodeBase64', 'some-base64-string')
````
and for the command to then use the supplied input string instead of opening the input box.

It is a small change for which I will provide a PR.

**Comment by JasonMejane** [comment]
Thanks for your contribution @LennartKoot !
I'm making a new realease including it 👍
