### ISSUE TITLE
[Feature Request] Add support to encode CSS, HTML and JavaScript files to base64

### ISSUE THREAD

**Issue by gusbemacbe** [JasonMejane/vscode-base64viewer#24]
Hello and good morning from Brazil! 

Please give a look at:

* CSS: https://base64.guru/converter/encode/css
* HTML: https://base64.guru/converter/encode/html

Then can you support to encode CSS, HTML and JavaScript files to base64? 

Thank you!

**Comment by JasonMejane** [comment]
Hello!
Thanks for your suggestion, I'll do my best to add those in a near future
